<a href="https://colab.research.google.com/github/saiprasanthreddy/ml-things/blob/main/chi_squre%2Canova_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**chi2- test
**

In [1]:
import scipy.stats as stats

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
data = sns.load_dataset("tips")

In [4]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
data_table = pd.crosstab(data["sex"], data["smoker"])
data_table

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [6]:
observed_valus = data_table.values
observed_valus

array([[60, 97],
       [33, 54]])

In [7]:
val = stats.chi2_contingency(data_table)
val

Chi2ContingencyResult(statistic=np.float64(0.0), pvalue=np.float64(1.0), dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

In [11]:
Expected_values = val[3]
Expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [12]:
no_of_rows = len(data_table.iloc[0:2,0])
no_of_columns = len(data_table.iloc[0,0:2])
ddof = (no_of_rows - 1) * (no_of_columns - 1)
print("Degree of Freedom: ", ddof)
alpha = 0.05

Degree of Freedom:  1

In [13]:
from scipy.stats import chi2
chi_square = sum([(o - e) ** 2. / e for o, e in zip(observed_valus, Expected_values)])
chi_square_statistic = chi_square[0] + chi_square[1]

In [14]:
print("chi-square statistic: ", chi_square_statistic)

chi-square statistic:  0.001934818536627623

In [15]:

critical_value = chi2.ppf(q = 1 - alpha, df = ddof)
print("Critical Value: ", critical_value)

Critical Value:  3.841458820694124

In [16]:
p_value = 1 - chi2.cdf(x = chi_square_statistic, df = ddof)
print("p-value: ", p_value)
print("Significance Level: ", alpha)
print("Degree of Freedom: ", ddof)

p-value:  0.964915107315732
Significance Level:  0.05
Degree of Freedom:  1

In [17]:
if chi_square_statistic >= critical_value:
    print("Reject H0, There is a relationship between 2 categorical variables")
else:
    print("Retain H0, There is no relationship between 2 categorical variables")

Retain H0, There is no relationship between 2 categorical variables

In [18]:
if p_value <= alpha:
    print("Reject H0, There is a relationship between 2 categorical variables")
else:
    print("Retain H0, There is no relationship between 2 categorical variables")

Retain H0, There is no relationship between 2 categorical variables

Anova

In [19]:
import seaborn as sns

df1= sns.load_dataset('iris')

In [20]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
df_anova = df1[['petal_width','species']]

In [22]:
grps = pd.unique(df_anova.species.values)


grps

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [23]:
d_data = {grp:df_anova['petal_width'][df_anova.species == grp] for grp in grps}

In [25]:
d_data

{'setosa': 0     0.2
 1     0.2
 2     0.2
 3     0.2
 4     0.2
 5     0.4
 6     0.3
 7     0.2
 8     0.2
 9     0.1
 10    0.2
 11    0.2
 12    0.1
 13    0.1
 14    0.2
 15    0.4
 16    0.4
 17    0.3
 18    0.3
 19    0.3
 20    0.2
 21    0.4
 22    0.2
 23    0.5
 24    0.2
 25    0.2
 26    0.4
 27    0.2
 28    0.2
 29    0.2
 30    0.2
 31    0.4
 32    0.1
 33    0.2
 34    0.2
 35    0.2
 36    0.2
 37    0.1
 38    0.2
 39    0.2
 40    0.3
 41    0.3
 42    0.2
 43    0.6
 44    0.4
 45    0.3
 46    0.2
 47    0.2
 48    0.2
 49    0.2
 Name: petal_width, dtype: float64,
 'versicolor': 50    1.4
 51    1.5
 52    1.5
 53    1.3
 54    1.5
 55    1.3
 56    1.6
 57    1.0
 58    1.3
 59    1.4
 60    1.0
 61    1.5
 62    1.0
 63    1.4
 64    1.3
 65    1.4
 66    1.5
 67    1.0
 68    1.5
 69    1.1
 70    1.8
 71    1.3
 72    1.5
 73    1.2
 74    1.3
 75    1.4
 76    1.4
 77    1.7
 78    1.5
 79    1.0
 80    1.1
 81    1.0
 82    1.2
 83    1.6
 84    1.5
 85    1.6
 86    1.5
 87    1.3
 88    1.3
 89    1.3
 90    1.2
 91    1.4
 92    1.2
 93    1.0
 94    1.3
 95    1.2
 96    1.3
 97    1.3
 98    1.1
 99    1.3
 Name: petal_width, dtype: float64,
 'virginica': 100    2.5
 101    1.9
 102    2.1
 103    1.8
 104    2.2
 105    2.1
 106    1.7
 107    1.8
 108    1.8
 109    2.5
 110    2.0
 111    1.9
 112    2.1
 113    2.0
 114    2.4
 115    2.3
 116    1.8
 117    2.2
 118    2.3
 119    1.5
 120    2.3
 121    2.0
 122    2.0
 123    1.8
 124    2.1
 125    1.8
 126    1.8
 127    1.8
 128    2.1
 129    1.6
 130    1.9
 131    2.0
 132    2.2
 133    1.5
 134    1.4
 135    2.3
 136    2.4
 137    1.8
 138    1.8
 139    2.1
 140    2.4
 141    2.3
 142    1.9
 143    2.3
 144    2.5
 145    2.3
 146    1.9
 147    2.0
 148    2.3
 149    1.8
 Name: petal_width, dtype: float64}

In [30]:
F, p = stats.f_oneway(d_data['setosa'], d_data['versicolor'], d_data['virginica'])

In [31]:
p

np.float64(4.169445839443833e-85)

In [32]:

F

np.float64(960.0071468018067)

In [33]:
if p<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

reject null hypothesis