<a href="https://colab.research.google.com/github/saiprasanthreddy/ml-things/blob/main/core_useage'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
#Dataset: https://archive.ics.uci.edu/ml/datasets/wine+quality
df=pd.read_csv("winequality-white.csv",sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [8]:
df['quality'].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [10]:
df.shape

(4898, 12)

In [11]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [12]:
### Get the dependent features
X=df.iloc[:,:-1]
X.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9

In [13]:
y=df.iloc[:,-1]
y.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

In [14]:
from time import time
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [15]:
## CPU cores we use n_jobs
model=RandomForestClassifier(n_estimators=100)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=1)
end_time=time()
print(end_time-start_time)

22.740995168685913

In [16]:
model=RandomForestClassifier(n_estimators=100)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=2)
end_time=time()
print(end_time-start_time)

21.6453115940094

In [17]:
model=RandomForestClassifier(n_estimators=100)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=4)
end_time=time()
print(end_time-start_time)

20.499476194381714

In [19]:
model=RandomForestClassifier(n_estimators=100)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
start_time=time()
n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=-1)
end_time=time()
print(end_time-start_time)

21.144201278686523

In [18]:
cores=[1,2,3,4,5,6,7,8,9]
for core in cores:
    model=RandomForestClassifier(n_estimators=100)
    #stratified K Fold
    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=4)
    start_time=time()
    n_scores =cross_val_score(model,df.iloc[:,:-1],df.iloc[:,-1],scoring='accuracy', cv=cv, n_jobs=core)
    end_time=time()
    total_time=end_time-start_time
    print("For Cores {} Training Time was {}secs".format(core,total_time))

For Cores 1 Training Time was 20.292023420333862secs
For Cores 2 Training Time was 15.53125secs
For Cores 3 Training Time was 17.532798528671265secs
For Cores 4 Training Time was 18.700226545333862secs
For Cores 5 Training Time was 17.864280700683594secs
For Cores 6 Training Time was 24.79536747932434secs
For Cores 7 Training Time was 16.56657838821411secs
For Cores 8 Training Time was 16.46487021446228secs
For Cores 9 Training Time was 18.978992223739624secs